#
# Module manifest for module 'xoap-application-packaging-dsc'
#
# Generated by: XOAP.io
#
# Generated on: 8/26/2022
#

$moduleName = '{ModuleName}'

$powerShellVersion = '5.1' # Must be 5.1 to support the property DscResourcesToExport. Change manually after.

# Temporarily install the module from the PowerShell Gallery to get the DSC resource names.
Install-Module -Name $moduleName -Scope CurrentUser
$dscResourcesToExport = (Get-DscResource -Module $moduleName).Name
Uninstall-Module -Name $moduleName -Force

$manifestPath = "source\$($moduleName).psd1"

$updateModuleManifestParameters = @{
    Author               = 'XOAP.io'
    CompanyName          = 'RIS AG'
    Copyright            = 'Copyright the XOAP.io contributors. All rights reserved.'
    DscResourcesToExport = $dscResourcesToExport
    IconUri              = ''
    LicenseUri           = "https://github.com/xoap-io/$moduleName/blob/master/LICENSE"
    Path                 = $manifestPath
    PreRelease           = ''
    ProjectUri           = "https://github.com/xoap-io/$moduleName"
    ReleaseNotes         = ' '
    ModuleVersion        = '0.0.1' # Module Version is now controlled by GitVersion
    PowerShellVersion    = $powerShellVersion
}

Update-ModuleManifest @updateModuleManifestParameters

@{

# Script module or binary module file associated with this manifest.
RootModule = 'xoap-application-packaging-dsc.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '94dad355-1841-478c-895e-87521226327a'

# Author of this module
Author = 'XOAP.io'

# Company or vendor of this module
CompanyName = 'RIS AG'

# Copyright statement for this module
Copyright = '(c) 2022 XOAP.io. All rights reserved.'

# Description of the functionality provided by this module
Description = 'DSC Module to prepare a Windows Machine for PSADT Application Packaging'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        Prerelease = ''
        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
